// Auto-generated by Supabase from the consolidated `tossup-cricket` project
// (byuvtmfarlreoxilrzcx). Regenerate with:
//   supabase gen types typescript --project-id byuvtmfarlreoxilrzcx
// or the Supabase MCP `generate_typescript_types`. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" }
  public: {
    Tables: {
      clubs: {
        Row: {
          id: string; name: string; slug: string | null; description: string | null
          owner_id: string | null; created_by: string | null
          location: string | null; city: string | null; region: string | null; country: string | null
          latitude: number | null; longitude: number | null
          website: string | null; contact_email: string | null; social_links: Json
          visibility: Database["public"]["Enums"]["visibility"]; max_members: number | null; settings: Json
          recognition_tier: Database["public"]["Enums"]["recognition_tier"]
          verified_at: string | null; verified_by: string | null; verification_source: string | null
          reputation_score: number; reputation_signals: Json
          is_recruiting: boolean; roles_needed: string[]; founded_year: number | null
          created_at: string; updated_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["clubs"]["Row"]> & { name: string }
        Update: Partial<Database["public"]["Tables"]["clubs"]["Row"]>
        Relationships: []
      }
      leagues: {
        Row: {
          id: string; name: string; description: string | null; code: string | null; type: string
          club_id: string | null; owner_id: string | null
          visibility: Database["public"]["Enums"]["visibility"]
          season: string | null; start_date: string | null; end_date: string | null; max_teams: number | null
          registration_url: string | null; registration_status: string
          rules_text: string | null; format: string | null; venue: string | null
          location: string | null; city: string | null; region: string | null; country: string | null
          latitude: number | null; longitude: number | null
          contact_info: Json; social_links: Json
          recognition_tier: Database["public"]["Enums"]["recognition_tier"]
          verified_at: string | null; verified_by: string | null; verification_source: string | null
          reputation_score: number
          points_win: number; points_tie: number; points_loss: number; points_noresult: number
          standings: Json; settings: Json; created_at: string; updated_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["leagues"]["Row"]> & { name: string }
        Update: Partial<Database["public"]["Tables"]["leagues"]["Row"]>
        Relationships: []
      }
      tournament_teams: {
        Row: {
          id: string; league_id: string; name: string; club_id: string | null
          captain_name: string | null; contact_email: string | null; contact_phone: string | null
          logo: string | null; color: string | null; club_team_id: string | null; created_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["tournament_teams"]["Row"]> & { league_id: string; name: string }
        Update: Partial<Database["public"]["Tables"]["tournament_teams"]["Row"]>
        Relationships: []
      }
      tournament_registrations: {
        Row: {
          id: string; league_id: string; team_name: string; club_id: string | null
          contact_name: string | null; contact_email: string | null; contact_phone: string | null
          status: string; notes: string | null; user_id: string | null; created_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["tournament_registrations"]["Row"]> & { league_id: string; team_name: string }
        Update: Partial<Database["public"]["Tables"]["tournament_registrations"]["Row"]>
        Relationships: []
      }
      fixtures: {
        Row: {
          id: string; league_id: string; match_number: number | null; round_label: string | null
          team_a_id: string | null; team_b_id: string | null; team_a_name: string | null; team_b_name: string | null
          venue: string | null; scheduled_at: string | null; status: string
          team_a_runs: number | null; team_a_wickets: number | null; team_a_overs: number | null
          team_b_runs: number | null; team_b_wickets: number | null; team_b_overs: number | null
          result_type: string | null; winner_team_id: string | null; result_note: string | null
          external_source: string | null; external_id: string | null; created_at: string; updated_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["fixtures"]["Row"]> & { league_id: string }
        Update: Partial<Database["public"]["Tables"]["fixtures"]["Row"]>
        Relationships: []
      }
      player_profiles: {
        Row: {
          id: string; user_id: string | null; display_name: string; photo: string | null
          city: string | null; region: string | null; country: string | null
          latitude: number | null; longitude: number | null
          primary_role: string | null; batting_style: string | null; bowling_style: string | null
          looking_for_club: boolean; availability: string | null; bio: string | null
          contact_email: string | null; contact_phone: string | null; current_club_id: string | null
          visibility: Database["public"]["Enums"]["visibility"]
          recognition_tier: Database["public"]["Enums"]["recognition_tier"]
          reputation_score: number; external_links: Json
          merged_into_id: string | null
          created_at: string; updated_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["player_profiles"]["Row"]> & { display_name: string }
        Update: Partial<Database["public"]["Tables"]["player_profiles"]["Row"]>
        Relationships: []
      }
      teams: {
        Row: { id: string; club_id: string; name: string; description: string | null; created_at: string; updated_at: string }
        Insert: Partial<Database["public"]["Tables"]["teams"]["Row"]> & { club_id: string; name: string }
        Update: Partial<Database["public"]["Tables"]["teams"]["Row"]>
        Relationships: []
      }
      club_memberships: {
        Row: { id: string; person_id: string; club_id: string; role: Database["public"]["Enums"]["organization_role"]; created_at: string }
        Insert: Partial<Database["public"]["Tables"]["club_memberships"]["Row"]> & { person_id: string; club_id: string }
        Update: Partial<Database["public"]["Tables"]["club_memberships"]["Row"]>
        Relationships: []
      }
      team_memberships: {
        Row: { id: string; person_id: string; team_id: string; role: Database["public"]["Enums"]["organization_role"]; created_at: string }
        Insert: Partial<Database["public"]["Tables"]["team_memberships"]["Row"]> & { person_id: string; team_id: string }
        Update: Partial<Database["public"]["Tables"]["team_memberships"]["Row"]>
        Relationships: []
      }
      league_memberships: {
        Row: { id: string; person_id: string; league_id: string; role: Database["public"]["Enums"]["organization_role"]; created_at: string }
        Insert: Partial<Database["public"]["Tables"]["league_memberships"]["Row"]> & { person_id: string; league_id: string }
        Update: Partial<Database["public"]["Tables"]["league_memberships"]["Row"]>
        Relationships: []
      }
      tournament_team_memberships: {
        Row: { id: string; person_id: string; tournament_team_id: string; role: Database["public"]["Enums"]["organization_role"]; created_at: string }
        Insert: Partial<Database["public"]["Tables"]["tournament_team_memberships"]["Row"]> & { person_id: string; tournament_team_id: string }
        Update: Partial<Database["public"]["Tables"]["tournament_team_memberships"]["Row"]>
        Relationships: []
      }
      external_sources: {
        Row: { id: string; key: string; name: string; type: string; base_url: string | null; default_tier: Database["public"]["Enums"]["recognition_tier"]; trusted: boolean; created_at: string }
        Insert: Partial<Database["public"]["Tables"]["external_sources"]["Row"]> & { key: string; name: string }
        Update: Partial<Database["public"]["Tables"]["external_sources"]["Row"]>
        Relationships: []
      }
      external_links: {
        Row: { id: string; source_id: string; entity_type: string; entity_id: string; external_id: string | null; external_url: string | null; raw: Json | null; last_synced_at: string | null; created_at: string }
        Insert: Partial<Database["public"]["Tables"]["external_links"]["Row"]> & { source_id: string; entity_type: string; entity_id: string }
        Update: Partial<Database["public"]["Tables"]["external_links"]["Row"]>
        Relationships: []
      }
      ingested_results: {
        Row: { id: string; source_id: string; external_id: string | null; payload: Json; status: string; mapped_fixture_id: string | null; fetched_at: string }
        Insert: Partial<Database["public"]["Tables"]["ingested_results"]["Row"]> & { source_id: string }
        Update: Partial<Database["public"]["Tables"]["ingested_results"]["Row"]>
        Relationships: []
      }
      users: {
        Row: { id: string; email: string | null; name: string | null; image: string | null; phone: string | null; bio: string | null; primary_person_id: string | null; created_at: string; updated_at: string }
        Insert: Partial<Database["public"]["Tables"]["users"]["Row"]> & { id: string }
        Update: Partial<Database["public"]["Tables"]["users"]["Row"]>
        Relationships: []
      }
      tournament_posts: {
        Row: {
          id: string; league_id: string
          kind: Database["public"]["Enums"]["post_kind"]
          priority: Database["public"]["Enums"]["post_priority"]
          title: string | null; body: string
          author_name: string | null; author_id: string | null; is_host: boolean
          is_pinned: boolean; pinned_at: string | null
          status: Database["public"]["Enums"]["flag_status"] | null
          expires_at: string | null; reply_count: number
          requires_ack: boolean; ack_count: number
          created_at: string; updated_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["tournament_posts"]["Row"]> & { league_id: string; body: string }
        Update: Partial<Database["public"]["Tables"]["tournament_posts"]["Row"]>
        Relationships: []
      }
      tournament_post_acks: {
        Row: {
          id: string; post_id: string; viewer_id: string; viewer_name: string | null; created_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["tournament_post_acks"]["Row"]> & { post_id: string; viewer_id: string }
        Update: Partial<Database["public"]["Tables"]["tournament_post_acks"]["Row"]>
        Relationships: []
      }
      tournament_post_replies: {
        Row: {
          id: string; post_id: string; body: string
          author_name: string | null; author_id: string | null; is_host: boolean; created_at: string
        }
        Insert: Partial<Database["public"]["Tables"]["tournament_post_replies"]["Row"]> & { post_id: string; body: string }
        Update: Partial<Database["public"]["Tables"]["tournament_post_replies"]["Row"]>
        Relationships: []
      }
    }
    Views: {
      tournament_standings: {
        Row: {
          league_id: string | null; team_id: string | null; name: string | null
          played: number | null; won: number | null; lost: number | null; tied: number | null; no_result: number | null
          runs_for: number | null; runs_against: number | null; points: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      km_between: { Args: { lat1: number; lon1: number; lat2: number; lon2: number }; Returns: number }
      is_scope_admin: { Args: { p_user: string; p_scope: string; p_scope_id: string }; Returns: boolean }
      approve_tournament_registration: { Args: { p_reg_id: string }; Returns: string }
      merge_persons: { Args: { p_loser: string; p_winner: string }; Returns: undefined }
    }
    Enums: {
      organization_role: "OWNER" | "ADMIN" | "MODERATOR" | "MEMBER"
      recognition_tier: "OFFICIAL" | "AFFILIATED" | "COMMUNITY" | "UNVERIFIED"
      visibility: "PUBLIC" | "PRIVATE"
      post_kind: "ANNOUNCEMENT" | "SCHEDULE" | "RESULT" | "ALERT" | "GENERAL" | "FLAG"
      post_priority: "LOW" | "NORMAL" | "HIGH" | "URGENT"
      flag_status: "OPEN" | "ACKNOWLEDGED" | "RESOLVED"
    }
    CompositeTypes: Record<string, never>
  }
}
